server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      discovery:
        enabled: false
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

  grpc:
    server:
      port: 9090
    client:
      auth-service:
        address: static://auth-service:6565
        enable-keep-alive: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      grpcPort: 9090