CREATE TABLE IF NOT EXISTS courses(
    id int primary key,
    name varchar(128),
    title varchar(128),
    description varchar(256),
    university varchar(16),
);

CREATE TABLE IF NOT EXISTS student_in_course (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(128),
    course_id int references courses(id)
);