#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"  # Порт вашего фронтенда
#            allowedMethods: "*"
#            allowedHeaders: "*"
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        # User
#        - id: user_service_route
#          uri: lb://user-service
#          predicates:
#            - Path=/api/v1/user/**
#
#        # Auth-service
#        - id: auth_service_route
#          uri: lb://auth-service
#          predicates:
#              - Path=/api/v1/auth/**